package com.cineflow.bug.service;
import com.cineflow.bug.dto.*; import com.cineflow.bug.entity.*; import com.cineflow.bug.exception.ResourceNotFoundException; import com.cineflow.bug.repository.*; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile;
@Service @RequiredArgsConstructor public class BugDetailService {
  private final BugService bugService; private final BugFrameRepository frames; private final FrameTypeRepository frameTypes; private final BugAnnotationRepository annotations; private final AnnotationTypeRepository annotationTypes; private final BugAttachmentRepository attachments; private final AttachmentTypeRepository attachmentTypes; private final BugReferenceRepository references; private final FileStorageService storage;
  @Transactional public FrameResponse addFrame(UUID bugId,FrameRequest r){bugService.entity(bugId);BugFrame f=new BugFrame();f.setBugId(bugId);f.setFrameNumber(r.frameNumber());f.setTimecode(r.timecode());f.setFrameType(frameTypes.findById(r.frameTypeId()).orElseThrow(()->new ResourceNotFoundException("Frame type not found")));f.setStartFrame(r.startFrame());f.setEndFrame(r.endFrame());return frame(frames.save(f));}
  @Transactional(readOnly=true) public List<FrameResponse> frames(UUID bugId){bugService.entity(bugId);return frames.findAllByBugIdOrderByCreatedAt(bugId).stream().map(this::frame).toList();}
  @Transactional public AnnotationResponse addAnnotation(UUID bugId,AnnotationRequest r){bugService.entity(bugId);BugAnnotation a=new BugAnnotation();a.setBugId(bugId);a.setFrameNumber(r.frameNumber());a.setAnnotationName(r.annotationName());a.setAnnotationType(annotationTypes.findById(r.annotationTypeId()).orElseThrow(()->new ResourceNotFoundException("Annotation type not found")));a.setReviewer(r.reviewer());a.setAnnotationData(r.annotationData());a.setImageUrl(r.imageUrl());return annotation(annotations.save(a));}
  @Transactional(readOnly=true) public List<AnnotationResponse> annotations(UUID bugId){bugService.entity(bugId);return annotations.findAllByBugIdOrderByCreatedAt(bugId).stream().map(this::annotation).toList();}
  @Transactional public FileResponse addAttachment(UUID bugId,AttachmentMetadata meta,MultipartFile file){bugService.entity(bugId);AttachmentType type=attachmentTypes.findById(meta.attachmentTypeId()).orElseThrow(()->new ResourceNotFoundException("Attachment type not found"));var stored=storage.store(file);try{BugAttachment a=new BugAttachment();a.setBugId(bugId);a.setAttachmentType(type);a.setFileName(stored.name());a.setFilePath(stored.relativePath());a.setFileUrl(meta.fileUrl());a.setMimeType(stored.contentType());a.setFileSize(stored.size());a.setDuration(meta.duration());return attachment(attachments.saveAndFlush(a));}catch(RuntimeException e){storage.delete(stored.relativePath());throw e;}}
  @Transactional public FileResponse addReference(UUID bugId,String fileUrl,MultipartFile file){bugService.entity(bugId);var stored=storage.store(file);try{BugReference r=new BugReference();r.setBugId(bugId);r.setFileName(stored.name());r.setFilePath(stored.relativePath());r.setFileUrl(fileUrl);r.setMimeType(stored.contentType());r.setFileSize(stored.size());return reference(references.saveAndFlush(r));}catch(RuntimeException e){storage.delete(stored.relativePath());throw e;}}
  @Transactional(readOnly=true) public List<FileResponse> files(UUID bugId){bugService.entity(bugId);List<FileResponse> result=new ArrayList<>();attachments.findAllByBugIdOrderByCreatedAt(bugId).stream().map(this::attachment).forEach(result::add);references.findAllByBugIdOrderByCreatedAt(bugId).stream().map(this::reference).forEach(result::add);return result;}
  @Transactional public void deleteFrame(UUID bugId,UUID id){bugService.entity(bugId);BugFrame f=frames.findById(id).filter(x->x.getBugId().equals(bugId)).orElseThrow(()->new ResourceNotFoundException("Frame not found"));frames.delete(f);}
  @Transactional public void deleteAnnotation(UUID bugId,UUID id){bugService.entity(bugId);BugAnnotation a=annotations.findById(id).filter(x->x.getBugId().equals(bugId)).orElseThrow(()->new ResourceNotFoundException("Annotation not found"));annotations.delete(a);}
  @Transactional public void deleteAttachment(UUID bugId,UUID id){bugService.entity(bugId);BugAttachment a=attachments.findById(id).filter(x->x.getBugId().equals(bugId)).orElseThrow(()->new ResourceNotFoundException("Attachment not found"));attachments.delete(a);storage.delete(a.getFilePath());}
  @Transactional public void deleteReference(UUID bugId,UUID id){bugService.entity(bugId);BugReference r=references.findById(id).filter(x->x.getBugId().equals(bugId)).orElseThrow(()->new ResourceNotFoundException("Reference not found"));references.delete(r);storage.delete(r.getFilePath());}
  private FrameResponse frame(BugFrame f){return new FrameResponse(f.getId(),f.getBugId(),f.getFrameNumber(),f.getTimecode(),BugService.lookup(f.getFrameType()),f.getStartFrame(),f.getEndFrame(),f.getCreatedAt());}
  private AnnotationResponse annotation(BugAnnotation a){return new AnnotationResponse(a.getId(),a.getBugId(),a.getFrameNumber(),a.getAnnotationName(),BugService.lookup(a.getAnnotationType()),a.getReviewer(),a.getAnnotationData(),a.getImageUrl(),a.getCreatedAt(),a.getUpdatedAt());}
  private FileResponse attachment(BugAttachment a){return new FileResponse(a.getId(),a.getBugId(),"ATTACHMENT",BugService.lookup(a.getAttachmentType()),a.getFileName(),a.getFilePath(),a.getFileUrl(),a.getMimeType(),a.getFileSize(),a.getDuration(),a.getCreatedAt());}
  private FileResponse reference(BugReference r){return new FileResponse(r.getId(),r.getBugId(),"REFERENCE",null,r.getFileName(),r.getFilePath(),r.getFileUrl(),r.getMimeType(),r.getFileSize(),null,r.getCreatedAt());}
}
