package com.cineflow.bug.service;
import com.cineflow.bug.dto.*; import com.cineflow.bug.entity.*; import com.cineflow.bug.exception.*; import com.cineflow.bug.repository.*; import java.time.Instant; import java.util.UUID; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class BugService {
  private final BugRepository bugs; private final DepartmentRepository departments; private final PriorityRepository priorities; private final SeverityRepository severities; private final BugStatusRepository statuses;
  @Transactional public BugResponse create(BugRequest r){ if(bugs.existsByBugKeyAndDeletedFalse(r.bugKey())) throw new BusinessValidationException("Bug key already exists"); Bug b=new Bug(); apply(b,r); return response(bugs.save(b)); }
  @Transactional(readOnly=true) public BugResponse get(UUID id){return response(entity(id));}
  @Transactional(readOnly=true) public Page<BugResponse> list(UUID versionId,Long statusId,Long priorityId,String query,Pageable pageable){ Specification<Bug> s=(root,c,cb)->cb.isFalse(root.get("deleted")); if(versionId!=null)s=s.and((root,c,cb)->cb.equal(root.get("versionId"),versionId)); if(statusId!=null)s=s.and((root,c,cb)->cb.equal(root.get("status").get("id"),statusId)); if(priorityId!=null)s=s.and((root,c,cb)->cb.equal(root.get("priority").get("id"),priorityId)); if(query!=null&&!query.isBlank()){String q="%"+query.toLowerCase()+"%";s=s.and((root,c,cb)->cb.or(cb.like(cb.lower(root.get("bugKey")),q),cb.like(cb.lower(root.get("title")),q)));} return bugs.findAll(s,pageable).map(this::response); }
  @Transactional public BugResponse update(UUID id,BugRequest r){Bug b=entity(id);if(bugs.existsByBugKeyAndIdNotAndDeletedFalse(r.bugKey(),id))throw new BusinessValidationException("Bug key already exists");apply(b,r);return response(bugs.save(b));}
  @Transactional public void delete(UUID id){Bug b=entity(id);b.setDeleted(true);b.setDeletedAt(Instant.now());bugs.save(b);}
  public Bug entity(UUID id){return bugs.findByIdAndDeletedFalse(id).orElseThrow(()->new ResourceNotFoundException("Bug not found: "+id));}
  private void apply(Bug b,BugRequest r){b.setVersionId(r.versionId());b.setBugKey(r.bugKey().trim());b.setTitle(r.title().trim());b.setDescription(r.description());b.setDepartment(find(departments,r.departmentId(),"Department"));b.setPriority(find(priorities,r.priorityId(),"Priority"));b.setSeverity(find(severities,r.severityId(),"Severity"));b.setStatus(find(statuses,r.statusId(),"Status"));b.setTags(r.tags());b.setNotes(r.notes());b.setReviewerComment(r.reviewerComment());b.setDueDate(r.dueDate());}
  private <T> T find(org.springframework.data.jpa.repository.JpaRepository<T,Long> repo,Long id,String type){if(id==null)return null;return repo.findById(id).orElseThrow(()->new ResourceNotFoundException(type+" not found: "+id));}
  public static LookupResponse lookup(LookupEntity e){if(e==null)return null;Integer sort=e instanceof Priority p?p.getSortOrder():e instanceof Severity s?s.getSortOrder():e instanceof BugStatus s?s.getSortOrder():null;return new LookupResponse(e.getId(),e.getCode(),e.getName(),e.getDescription(),e.isActive(),sort);}
  private BugResponse response(Bug b){return new BugResponse(b.getId(),b.getVersionId(),b.getBugKey(),b.getTitle(),b.getDescription(),lookup(b.getDepartment()),lookup(b.getPriority()),lookup(b.getSeverity()),lookup(b.getStatus()),b.getTags(),b.getNotes(),b.getReviewerComment(),b.getDueDate(),b.getCreatedAt(),b.getUpdatedAt(),b.getVersion());}
}
