package com.cineflow.bug.service;
import com.cineflow.bug.exception.BusinessValidationException; import java.io.IOException; import java.nio.file.*; import java.time.*; import java.time.format.DateTimeFormatter; import java.util.UUID; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.web.multipart.MultipartFile;
@Service public class FileStorageService {
  private static final DateTimeFormatter TS=DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmssSSS'Z'").withZone(ZoneOffset.UTC); private final Path root;
  public FileStorageService(@Value("${app.storage.attachment-location}")String location){root=Path.of(location).toAbsolutePath().normalize();}
  public StoredFile store(MultipartFile file){if(file==null||file.isEmpty())throw new BusinessValidationException("File is required");String supplied=file.getOriginalFilename();if(supplied==null||supplied.isBlank())throw new BusinessValidationException("File name is required");String normalized=supplied.replace('\\','/');String name=normalized.substring(normalized.lastIndexOf('/')+1);if(name.isBlank()||name.equals(".")||name.equals(".."))throw new BusinessValidationException("Invalid file name");String folder=TS.format(Instant.now())+"-"+UUID.randomUUID();Path dir=root.resolve(folder).normalize(),target=dir.resolve(name).normalize();if(!target.startsWith(dir)||!dir.startsWith(root))throw new BusinessValidationException("Invalid file name");try{Files.createDirectories(dir);try(var in=file.getInputStream()){Files.copy(in,target);}return new StoredFile(name,folder+"/"+name,file.getContentType(),file.getSize());}catch(IOException e){try{Files.deleteIfExists(target);Files.deleteIfExists(dir);}catch(IOException cleanup){e.addSuppressed(cleanup);}throw new IllegalStateException("Could not store uploaded file",e);}}
  public void delete(String relative){if(relative==null)return;Path file=root.resolve(relative).normalize();if(!file.startsWith(root))return;try{Files.deleteIfExists(file);Path parent=file.getParent();if(parent!=null&&!parent.equals(root))Files.deleteIfExists(parent);}catch(IOException ignored){}}
  public record StoredFile(String name,String relativePath,String contentType,long size){}
}
