CREATE TABLE departments (id BIGINT NOT NULL AUTO_INCREMENT,code VARCHAR(50) NOT NULL,name VARCHAR(100) NOT NULL,description VARCHAR(500),active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_departments_code(code),UNIQUE KEY uk_departments_name(name));
CREATE TABLE priorities (id BIGINT NOT NULL AUTO_INCREMENT,code VARCHAR(50) NOT NULL,name VARCHAR(100) NOT NULL,description VARCHAR(500),sort_order INT NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_priorities_code(code),UNIQUE KEY uk_priorities_name(name));
CREATE TABLE severities (id BIGINT NOT NULL AUTO_INCREMENT,code VARCHAR(50) NOT NULL,name VARCHAR(100) NOT NULL,description VARCHAR(500),sort_order INT NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_severities_code(code),UNIQUE KEY uk_severities_name(name));
CREATE TABLE bug_statuses (id BIGINT NOT NULL AUTO_INCREMENT,code VARCHAR(50) NOT NULL,name VARCHAR(100) NOT NULL,description VARCHAR(500),sort_order INT NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_bug_statuses_code(code),UNIQUE KEY uk_bug_statuses_name(name));
CREATE TABLE attachment_types (id BIGINT NOT NULL AUTO_INCREMENT,code VARCHAR(50) NOT NULL,name VARCHAR(100) NOT NULL,description VARCHAR(500),active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_attachment_types_code(code),UNIQUE KEY uk_attachment_types_name(name));
CREATE TABLE frame_types (id BIGINT NOT NULL AUTO_INCREMENT,code VARCHAR(50) NOT NULL,name VARCHAR(100) NOT NULL,description VARCHAR(500),active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_frame_types_code(code),UNIQUE KEY uk_frame_types_name(name));
CREATE TABLE annotation_types (id BIGINT NOT NULL AUTO_INCREMENT,code VARCHAR(50) NOT NULL,name VARCHAR(100) NOT NULL,description VARCHAR(500),active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_annotation_types_code(code),UNIQUE KEY uk_annotation_types_name(name));

CREATE TABLE bugs (id BINARY(16) NOT NULL,version_id BINARY(16) NOT NULL,bug_key VARCHAR(100) NOT NULL,title VARCHAR(255) NOT NULL,description LONGTEXT,department_id BIGINT,priority_id BIGINT,severity_id BIGINT,status_id BIGINT NOT NULL,tags LONGTEXT,notes LONGTEXT,reviewer_comment LONGTEXT,due_date DATE,created_at DATETIME(6) NOT NULL,updated_at DATETIME(6),created_by BINARY(16),updated_by BINARY(16),version BIGINT,deleted BOOLEAN NOT NULL DEFAULT FALSE,deleted_at DATETIME(6),PRIMARY KEY(id),UNIQUE KEY uk_bugs_bug_key(bug_key),KEY idx_bugs_version_id(version_id),KEY idx_bugs_status_id(status_id),CONSTRAINT fk_bugs_department FOREIGN KEY(department_id) REFERENCES departments(id),CONSTRAINT fk_bugs_priority FOREIGN KEY(priority_id) REFERENCES priorities(id),CONSTRAINT fk_bugs_severity FOREIGN KEY(severity_id) REFERENCES severities(id),CONSTRAINT fk_bugs_status FOREIGN KEY(status_id) REFERENCES bug_statuses(id));
CREATE TABLE bug_frames (id BINARY(16) NOT NULL,bug_id BINARY(16) NOT NULL,frame_number BIGINT,timecode VARCHAR(50),frame_type_id BIGINT NOT NULL,start_frame BIGINT,end_frame BIGINT,created_at DATETIME(6) NOT NULL,updated_at DATETIME(6),created_by BINARY(16),updated_by BINARY(16),version BIGINT,PRIMARY KEY(id),KEY idx_bug_frames_bug_id(bug_id),CONSTRAINT fk_bug_frames_bug FOREIGN KEY(bug_id) REFERENCES bugs(id) ON DELETE CASCADE,CONSTRAINT fk_bug_frames_type FOREIGN KEY(frame_type_id) REFERENCES frame_types(id));
CREATE TABLE bug_references (id BINARY(16) NOT NULL,bug_id BINARY(16) NOT NULL,file_name VARCHAR(500) NOT NULL,file_url VARCHAR(1000),file_path VARCHAR(1000) NOT NULL,file_size BIGINT,mime_type VARCHAR(255),created_at DATETIME(6) NOT NULL,updated_at DATETIME(6),created_by BINARY(16),updated_by BINARY(16),version BIGINT,PRIMARY KEY(id),KEY idx_bug_references_bug_id(bug_id),CONSTRAINT fk_bug_references_bug FOREIGN KEY(bug_id) REFERENCES bugs(id) ON DELETE CASCADE);
CREATE TABLE bug_attachments (id BINARY(16) NOT NULL,bug_id BINARY(16) NOT NULL,attachment_type_id BIGINT NOT NULL,file_name VARCHAR(500) NOT NULL,file_url VARCHAR(1000),file_path VARCHAR(1000) NOT NULL,mime_type VARCHAR(255),file_size BIGINT,duration DECIMAL(12,3),created_at DATETIME(6) NOT NULL,updated_at DATETIME(6),created_by BINARY(16),updated_by BINARY(16),version BIGINT,PRIMARY KEY(id),KEY idx_bug_attachments_bug_id(bug_id),CONSTRAINT fk_bug_attachments_bug FOREIGN KEY(bug_id) REFERENCES bugs(id) ON DELETE CASCADE,CONSTRAINT fk_bug_attachments_type FOREIGN KEY(attachment_type_id) REFERENCES attachment_types(id));
CREATE TABLE bug_annotations (id BINARY(16) NOT NULL,bug_id BINARY(16) NOT NULL,frame_number BIGINT,annotation_name VARCHAR(255) NOT NULL,annotation_type_id BIGINT NOT NULL,reviewer VARCHAR(255),annotation_data JSON,image_url VARCHAR(1000),created_at DATETIME(6) NOT NULL,updated_at DATETIME(6),created_by BINARY(16),updated_by BINARY(16),version BIGINT,PRIMARY KEY(id),KEY idx_bug_annotations_bug_id(bug_id),CONSTRAINT fk_bug_annotations_bug FOREIGN KEY(bug_id) REFERENCES bugs(id) ON DELETE CASCADE,CONSTRAINT fk_bug_annotations_type FOREIGN KEY(annotation_type_id) REFERENCES annotation_types(id));

INSERT INTO departments(code,name,description,active,created_at) VALUES ('EDIT','Editor','Video editing department',TRUE,NOW(6)),('COMP','Compositing','Compositing and VFX department',TRUE,NOW(6)),('ANIM','Animation','Animation department',TRUE,NOW(6)),('LIGHT','Lighting','Lighting department',TRUE,NOW(6)),('ROTO','Rotoscopy','Rotoscopy department',TRUE,NOW(6)),('MATCH','Matchmove','Matchmove and tracking department',TRUE,NOW(6)),('COLOR','Color','Color grading department',TRUE,NOW(6)),('SOUND','Sound','Sound and audio department',TRUE,NOW(6));
INSERT INTO priorities(code,name,description,sort_order,active,created_at) VALUES ('LOW','Low','Low priority issue',1,TRUE,NOW(6)),('MEDIUM','Medium','Normal priority issue',2,TRUE,NOW(6)),('HIGH','High','High priority issue',3,TRUE,NOW(6)),('URGENT','Urgent','Requires immediate attention',4,TRUE,NOW(6));
INSERT INTO severities(code,name,description,sort_order,active,created_at) VALUES ('TRIVIAL','Trivial','Very minor issue',1,TRUE,NOW(6)),('MINOR','Minor','Small issue with limited impact',2,TRUE,NOW(6)),('MAJOR','Major','Significant issue affecting the work',3,TRUE,NOW(6)),('CRITICAL','Critical','Severe issue requiring immediate correction',4,TRUE,NOW(6)),('BLOCKER','Blocker','Prevents further work or delivery',5,TRUE,NOW(6));
INSERT INTO bug_statuses(code,name,description,sort_order,active,created_at) VALUES ('OPEN','Open','Bug has been created',1,TRUE,NOW(6)),('IN_PROGRESS','In Progress','Bug is currently being worked on',2,TRUE,NOW(6)),('FIXED','Fixed','Bug has been fixed',3,TRUE,NOW(6)),('REOPENED','Reopened','Previously fixed bug was reopened',4,TRUE,NOW(6)),('VERIFIED','Verified','Fix has been verified',5,TRUE,NOW(6)),('CLOSED','Closed','Bug has been completed',6,TRUE,NOW(6)),('REJECTED','Rejected','Bug was rejected',7,TRUE,NOW(6));
INSERT INTO attachment_types(code,name,description,active,created_at) VALUES ('VOICE_NOTE','Voice Note','Audio recording',TRUE,NOW(6)),('CAMERA_NOTE','Camera Note','Camera-related recording',TRUE,NOW(6)),('SCREEN','Screen','Screen recording or screenshot',TRUE,NOW(6)),('REFERENCE','Reference','Reference file',TRUE,NOW(6));
INSERT INTO frame_types(code,name,description,active,created_at) VALUES ('SINGLE','Single Frame','One frame',TRUE,NOW(6)),('RANGE','Frame Range','Range of frames',TRUE,NOW(6)),('MULTIPLE','Multiple Frames','Multiple individual frames',TRUE,NOW(6));
INSERT INTO annotation_types(code,name,description,active,created_at) VALUES ('RECTANGLE','Rectangle','Rectangular annotation',TRUE,NOW(6)),('CIRCLE','Circle','Circular annotation',TRUE,NOW(6)),('ARROW','Arrow','Arrow annotation',TRUE,NOW(6)),('LINE','Line','Line annotation',TRUE,NOW(6)),('FREEHAND','Freehand','Freehand drawing',TRUE,NOW(6)),('TEXT','Text','Text annotation',TRUE,NOW(6));
